'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Piano.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39148__jobro__piano_ff_001() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39148__jobro__piano_ff_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39149__jobro__piano_ff_002() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39149__jobro__piano_ff_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39150__jobro__piano_ff_003() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39150__jobro__piano_ff_003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39151__jobro__piano_ff_004() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39151__jobro__piano_ff_004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39152__jobro__piano_ff_005() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39152__jobro__piano_ff_005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39153__jobro__piano_ff_006() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39153__jobro__piano_ff_006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39154__jobro__piano_ff_007() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39154__jobro__piano_ff_007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39155__jobro__piano_ff_008() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39155__jobro__piano_ff_008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39156__jobro__piano_ff_009() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39156__jobro__piano_ff_009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39157__jobro__piano_ff_010() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39157__jobro__piano_ff_010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39158__jobro__piano_ff_011() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39158__jobro__piano_ff_011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39159__jobro__piano_ff_012() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39159__jobro__piano_ff_012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39160__jobro__piano_ff_013() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39160__jobro__piano_ff_013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39161__jobro__piano_ff_014() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39161__jobro__piano_ff_014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39162__jobro__piano_ff_015() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39162__jobro__piano_ff_015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39163__jobro__piano_ff_016() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39163__jobro__piano_ff_016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39164__jobro__piano_ff_017() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39164__jobro__piano_ff_017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39165__jobro__piano_ff_018() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39165__jobro__piano_ff_018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39166__jobro__piano_ff_019() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39166__jobro__piano_ff_019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39167__jobro__piano_ff_020() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39167__jobro__piano_ff_020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39168__jobro__piano_ff_021() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39168__jobro__piano_ff_021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39169__jobro__piano_ff_022() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39169__jobro__piano_ff_022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39170__jobro__piano_ff_023() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39170__jobro__piano_ff_023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39171__jobro__piano_ff_024() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39171__jobro__piano_ff_024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39172__jobro__piano_ff_025() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39172__jobro__piano_ff_025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39173__jobro__piano_ff_026() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39173__jobro__piano_ff_026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39174__jobro__piano_ff_027() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39174__jobro__piano_ff_027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39175__jobro__piano_ff_028() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39175__jobro__piano_ff_028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39176__jobro__piano_ff_029() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39176__jobro__piano_ff_029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39177__jobro__piano_ff_030() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39177__jobro__piano_ff_030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39178__jobro__piano_ff_031() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39178__jobro__piano_ff_031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39179__jobro__piano_ff_032() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39179__jobro__piano_ff_032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39180__jobro__piano_ff_033() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39180__jobro__piano_ff_033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39181__jobro__piano_ff_034() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39181__jobro__piano_ff_034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39182__jobro__piano_ff_035() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39182__jobro__piano_ff_035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39183__jobro__piano_ff_036() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39183__jobro__piano_ff_036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39184__jobro__piano_ff_037() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39184__jobro__piano_ff_037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39185__jobro__piano_ff_038() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39185__jobro__piano_ff_038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39186__jobro__piano_ff_039() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39186__jobro__piano_ff_039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39187__jobro__piano_ff_040() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39187__jobro__piano_ff_040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39188__jobro__piano_ff_041() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39188__jobro__piano_ff_041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39189__jobro__piano_ff_042() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39189__jobro__piano_ff_042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39190__jobro__piano_ff_043() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39190__jobro__piano_ff_043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39191__jobro__piano_ff_044() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39191__jobro__piano_ff_044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39193__jobro__piano_ff_045() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39193__jobro__piano_ff_045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39194__jobro__piano_ff_046() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39194__jobro__piano_ff_046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39195__jobro__piano_ff_047() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39195__jobro__piano_ff_047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39196__jobro__piano_ff_048() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39196__jobro__piano_ff_048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39197__jobro__piano_ff_049() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39197__jobro__piano_ff_049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39198__jobro__piano_ff_050() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39198__jobro__piano_ff_050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39199__jobro__piano_ff_051() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39199__jobro__piano_ff_051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39200__jobro__piano_ff_052() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39200__jobro__piano_ff_052", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39201__jobro__piano_ff_053() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39201__jobro__piano_ff_053", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39202__jobro__piano_ff_054() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39202__jobro__piano_ff_054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39203__jobro__piano_ff_055() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39203__jobro__piano_ff_055", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39204__jobro__piano_ff_056() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39204__jobro__piano_ff_056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39205__jobro__piano_ff_057() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39205__jobro__piano_ff_057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39206__jobro__piano_ff_058() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39206__jobro__piano_ff_058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39207__jobro__piano_ff_059() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39207__jobro__piano_ff_059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39208__jobro__piano_ff_060() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39208__jobro__piano_ff_060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39209__jobro__piano_ff_061() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39209__jobro__piano_ff_061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39210__jobro__piano_ff_062() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39210__jobro__piano_ff_062", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39211__jobro__piano_ff_063() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39211__jobro__piano_ff_063", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39212__jobro__piano_ff_064() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39212__jobro__piano_ff_064", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39213__jobro__piano_ff_065() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39213__jobro__piano_ff_065", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39214__jobro__piano_ff_066() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39214__jobro__piano_ff_066", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39215__jobro__piano_ff_067() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39215__jobro__piano_ff_067", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _39216__jobro__piano_ff_068() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_39216__jobro__piano_ff_068", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
